# Generated by Django 4.0.3 on 2022-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_user_farmer_farmer_farmer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=True),
        ),
    ]
